import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NavbarComponent } from "@/shared/components/navbar/NavbarComponent";
import { ChangeTheme } from "@/shared/services/ChangeMode";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `min-h-screen bg-background font-sans antialiased transition-all duration-200`,
          fontSans.variable
        )}
      >
        <NavbarComponent />
        {children}
        <ChangeTheme />
      </body>
    </html>
  );
}
